using System;
using System.IO;
using System.Management;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Windows.Storage;

namespace VrcKaihenManager.Services;

public sealed class UnityEditorBridgeService
{
    private const string PackageName = "com.vrckaihenmanager.import-bridge";
    private const string PackageManifest = """
{
  "name": "com.vrckaihenmanager.import-bridge",
  "version": "1.2.0",
  "displayName": "VrcKaihenManager Import Bridge",
  "description": "Editor bridge used by VrcKaihenManager to import Unity packages into the active project.",
  "unity": "2022.3"
}
""";

    private const string BridgeSource = """
// Generated by VrcKaihenManager. This file enables imports requested by the desktop app.
#if UNITY_EDITOR
using System;
using System.IO;
using UnityEditor;
using UnityEngine;

[InitializeOnLoad]
internal static class VrcKaihenManagerPackageImportBridge
{
    private static readonly string RequestPath = Path.Combine(
        Directory.GetParent(Application.dataPath).FullName,
        "Library", "VrcKaihenManager", "import-request.txt");
    private static double _nextCheck;
    private static string _pendingPackagePath;

    static VrcKaihenManagerPackageImportBridge()
    {
        EditorApplication.update += CheckForImportRequest;
        AssetDatabase.importPackageStarted += name => Debug.Log("VrcKaihenManager: import started: " + name);
        AssetDatabase.importPackageCompleted += name => Debug.Log("VrcKaihenManager: import completed: " + name);
        AssetDatabase.importPackageCancelled += name => Debug.Log("VrcKaihenManager: import cancelled: " + name);
        AssetDatabase.importPackageFailed += (name, error) => Debug.LogError("VrcKaihenManager: import failed: " + name + " / " + error);
    }

    private static void CheckForImportRequest()
    {
        if (EditorApplication.timeSinceStartup < _nextCheck) return;
        _nextCheck = EditorApplication.timeSinceStartup + 0.5;
        if (EditorApplication.isCompiling || EditorApplication.isUpdating || !File.Exists(RequestPath)) return;
        try
        {
            var packagePath = File.ReadAllText(RequestPath).Trim();
            File.Delete(RequestPath);
            if (!string.IsNullOrWhiteSpace(packagePath) && File.Exists(packagePath))
            {
                _pendingPackagePath = packagePath;
                Debug.Log("VrcKaihenManager: import queued: " + packagePath);
                EditorApplication.delayCall += BeginImport;
            }
            else Debug.LogError("VrcKaihenManager: import package was not found: " + packagePath);
        }
        catch (Exception exception) { Debug.LogException(exception); }
    }

    private static void BeginImport()
    {
        var packagePath = _pendingPackagePath;
        _pendingPackagePath = null;
        if (string.IsNullOrWhiteSpace(packagePath) || !File.Exists(packagePath))
        {
            Debug.LogError("VrcKaihenManager: queued package was not found: " + packagePath);
            return;
        }
        Debug.Log("VrcKaihenManager: opening import dialog: " + packagePath);
        AssetDatabase.ImportPackage(packagePath, true);
    }
}
#endif
""";

    public async Task<string> RequestImportAsync(int unityProcessId, string packagePath)
    {
        var projectPath = ReadProjectPath(unityProcessId)
            ?? throw new InvalidOperationException("起動中のUnity Editorからプロジェクトパスを取得できません。");
        if (!Directory.Exists(Path.Combine(projectPath, "Assets"))
            || !Directory.Exists(Path.Combine(projectPath, "ProjectSettings")))
            throw new DirectoryNotFoundException($"Unityプロジェクトを確認できません: {projectPath}");

        var projectFolder = await StorageFolder.GetFolderFromPathAsync(projectPath);
        var packagesFolder = await projectFolder.CreateFolderAsync("Packages", CreationCollisionOption.OpenIfExists);
        var packageFolder = await packagesFolder.CreateFolderAsync(PackageName, CreationCollisionOption.OpenIfExists);
        var manifest = await packageFolder.CreateFileAsync("package.json", CreationCollisionOption.OpenIfExists);
        if (await FileIO.ReadTextAsync(manifest) != PackageManifest) await FileIO.WriteTextAsync(manifest, PackageManifest);
        var editorFolder = await packageFolder.CreateFolderAsync("Editor", CreationCollisionOption.OpenIfExists);
        var bridgeFile = await editorFolder.CreateFileAsync("VrcKaihenManagerImportBridge.cs", CreationCollisionOption.OpenIfExists);
        if (await FileIO.ReadTextAsync(bridgeFile) != BridgeSource) await FileIO.WriteTextAsync(bridgeFile, BridgeSource);
        await RemoveLegacyAssetsBridgeAsync(projectFolder);

        var libraryFolder = await projectFolder.GetFolderAsync("Library");
        var requestFolder = await libraryFolder.CreateFolderAsync("VrcKaihenManager", CreationCollisionOption.OpenIfExists);
        var requestFile = await requestFolder.CreateFileAsync("import-request.txt", CreationCollisionOption.ReplaceExisting);
        await FileIO.WriteTextAsync(requestFile, packagePath);
        return projectPath;
    }

    private static async Task RemoveLegacyAssetsBridgeAsync(StorageFolder projectFolder)
    {
        try
        {
            var assetsFolder = await projectFolder.GetFolderAsync("Assets");
            if (await assetsFolder.TryGetItemAsync("Editor") is not StorageFolder editorFolder) return;
            var legacyFolder = await editorFolder.TryGetItemAsync("VrcKaihenManager");
            if (legacyFolder is not null) await legacyFolder.DeleteAsync(StorageDeleteOption.PermanentDelete);
            var legacyMeta = await editorFolder.TryGetItemAsync("VrcKaihenManager.meta");
            if (legacyMeta is not null) await legacyMeta.DeleteAsync(StorageDeleteOption.PermanentDelete);
            if ((await editorFolder.GetItemsAsync()).Count != 0) return;
            await editorFolder.DeleteAsync(StorageDeleteOption.PermanentDelete);
            var editorMeta = await assetsFolder.TryGetItemAsync("Editor.meta");
            if (editorMeta is not null) await editorMeta.DeleteAsync(StorageDeleteOption.PermanentDelete);
        }
        catch (FileNotFoundException) { }
    }

    private static string? ReadProjectPath(int processId)
    {
        using var searcher = new ManagementObjectSearcher($"SELECT CommandLine FROM Win32_Process WHERE ProcessId = {processId}");
        foreach (ManagementObject process in searcher.Get())
        {
            var commandLine = process["CommandLine"] as string;
            if (string.IsNullOrWhiteSpace(commandLine)) continue;
            var match = Regex.Match(commandLine,
                "(?:^|\\s)\"?-projectPath\"?\\s+(?:\"(?<quoted>[^\"]+)\"|(?<plain>\\S+))",
                RegexOptions.IgnoreCase);
            if (!match.Success) continue;
            return (match.Groups["quoted"].Success ? match.Groups["quoted"].Value : match.Groups["plain"].Value)
                .Replace('/', Path.DirectorySeparatorChar);
        }
        return null;
    }
}
